### ISSUE TITLE
Telefonski Imenik - nova metoda

### ISSUE THREAD

**Issue by icsoft-rs** [icsoft-rs/phonebook#2]
Potrebno je dodati novu metodu za mnozenje dva decimalna broja. Ovlo je prilicno hitno, push-ujte izmene do kraja dana ako je to izvodljivo jer sutra ujutru imamo demo za potencijalne klijente.

**Comment by TijanaIc** [comment]
Done

**Comment by icsoft-rs** [comment]
Great job Tijana.
